# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Genesis/graduate/school2016_2017/blok 07/PROGH1/programs/full_adder/full_adder.cache/wt} [current_project]
set_property parent.project_path {D:/Genesis/graduate/school2016_2017/blok 07/PROGH1/programs/full_adder/full_adder.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/Genesis/graduate/school2016_2017/blok 07/PROGH1/programs/full_adder/full_adder.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {{D:/Genesis/graduate/school2016_2017/blok 07/PROGH1/programs/full_adder/full_adder.srcs/sources_1/new/top.vhd}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Genesis/graduate/school2016_2017/blok 07/PROGH1/programs/full_adder/full_adder.srcs/constrs_1/new/consts.xdc}}
set_property used_in_implementation false [get_files {{D:/Genesis/graduate/school2016_2017/blok 07/PROGH1/programs/full_adder/full_adder.srcs/constrs_1/new/consts.xdc}}]


synth_design -top top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
